<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CL_CLegendary_Launcher_</RootNamespace>
    <AssemblyName>CL.Core</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NeutralLanguage>uk-UA</NeutralLanguage>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CL.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="CmlLib.Core.Installer.Forge" Version="1.1.1" />
    <PackageReference Include="CmlLib.Core.Installer.NeoForge" Version="4.0.1" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Optifine.Installer" Version="1.0.1" />
    <PackageReference Include="Sentry" Version="6.8.0" />
    <PackageReference Include="SharpCompress" Version="0.50.1" />
  </ItemGroup>

</Project>
